// applications/apps/auth/ui/src/layout/content/container/login.svelte
<script lang="ts">
    import { Store } from "@wraithlight/core.redux";
    import { AuthAction } from "@wraithlight/common.auth-sdk.client";
    const store = Store.getInstance();

    let username = "";
    let password = "";
    function tryLogin(): void {
        store.dispatch(AuthAction.login(username, password));
    }
</script>

<div class="login-container">
    <h1>Log In</h1>
    <table>
        <tr>
            <td>
                Username
            </td>
            <td>
                <input type="text" bind:value={username}>
            </td>
        </tr>
        <tr>
            <td>
                Password
            </td>
            <td>
                <input type="password" bind:value={password}>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <button on:click={tryLogin}>Submit</button>
            </td>
        </tr>
    </table>
</div>


<style>
    .login-container {
        width: 80%;
        border: 1px solid var(--primary);
        height: 500px;
        margin-top: 4rem;
        padding: 2rem;
        box-sizing: border-box;
    }
    h1 {
        outline: none;
    }
</style>

// applications/apps/website/ui/src/app/modules/shared/login/login.component.ts
import { Component, OnDestroy, ViewEncapsulation } from "@angular/core";
import { AuthAction, AuthSelector } from "@wraithlight/common.auth-sdk.client";
import { Store } from "@wraithlight/core.redux";

import { WebsiteGlobalState } from "../../../../sdk";

@Component({
    selector: "wl-login",
    templateUrl: "./login.component.html",
    styleUrls: [
        "./login.component.scss"
    ],
    encapsulation: ViewEncapsulation.Emulated
})
export class LoginComponent implements OnDestroy {

    private readonly _store = Store.getInstance<WebsiteGlobalState>();
    private readonly _stopFns: Array<() => void> = [];

    public isBusy = false;

    public username = "";
    public password = "";

    constructor() {
        this._store
            .select(AuthSelector.isBusy)
            .onSelection((val, stopFn) => {
                this.isBusy = val;
                this._stopFns.push(stopFn);
            })
        ;
    }

    public ngOnDestroy(): void {
        this._stopFns.forEach(m => m());
    }

    public onSubmit(): void {
        this._store.dispatch(AuthAction.login(this.username, this.password));
    }

}

<div class="login-container">
    <div class="login-container-row">
        <input
            [disabled]="isBusy"
            type="text"
            [(ngModel)]="username"
        />
    </div>
    <div class="login-container-row">
        <input
            [disabled]="isBusy"
            type="password"
            [(ngModel)]="password"
        />
    </div>
    <div class="login-container-options">
        <button
            [disabled]="isBusy"
            type="button"
            (click)="onSubmit()"
        >
                Submit
        </button>
    </div>
</div>
